spring:
  application:
    name: api
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888

# TODO 환경별 프로퍼티 파일 분리
#spring:
#  profiles:
#    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:tc:mysql:8://testDB
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n"
  level:
    org.hibernate.type.descriptor.sql: TRACE

    # Flyway
    org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor: DEBUG
