server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:jsyang-dev/kids-planner-config.git
          default-label: master
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIAlTUTxJHU/MTDGImj5XuTH0QEn2Kxs7+lb5RN49GUkcoAoGCCqGSM49
            AwEHoUQDQgAEYeR6B8DwwNh0j8pGxVgffoYJf6yGOuviAaREy0m5PQt6hboe6bqZ
            7p//gd4ybPiv52HXMd/I/NBm1xWkkBkPmg==
            -----END EC PRIVATE KEY-----
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          host-key-algorithm: ecdsa-sha2-nistp256
