server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jsyang-dev/kids-planner-config.git
          default-label: master
